<h1>Policy Crud Operations</h1>

<p>
    <a class="btn btn-info pull-right" href="<?= $this->url('policy', ['action'=>'add']); ?>">Add Policy</a>
</p>

<table class="table table-striped">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Policy Number</th>
        <th>Start Date</th>
        <th>End Date</th>
        <th>Premium</th>
        <th>Action</th>
    </tr>
    <?php /* @var $policy \Application\Entity\Policy */?>
    <?php foreach ($this->routers as $key => $policy):
            $counter = ++$key;
            $counter += (($page > 1) ? (($page - 1) * $pageSize) : 0);
        ?>
        <tr>
            <td><?=$policy->getFirstName(); ?></td>
            <td><?=$policy->getLastName(); ?></td>
            <td><?=$policy->getPolicyNumber(); ?></td>
            <td><?=$policy->getStartDate(); ?></td>            
            <td><?=$policy->getEndDate(); ?></td>            
            <td><?=$policy->getPremium(); ?></td>            
            <td>
                <a class="btn btn-info" href="<?= $this->url('policy',
                    ['action'=>'edit', 'id'=>$policy->getId()]); ?>">
                    Edit
                </a>
                <a class="btn btn-danger" href="<?= $this->url('policy',
                    ['action'=>'delete', 'id'=> $policy->getId()]); ?>">
                    Delete
                </a>
            </td>
        </tr>
    <?php endforeach;?>
</table>

<script>
    var pageSizeSelector = document.getElementById("pageSizeSelector");
    pageSizeSelector.addEventListener("change", function() {
       var baseUrl = window.location.protocol + '//' + window.location.host + window.location.pathname;
       window.location.href = baseUrl +  '?pageSize=' + pageSizeSelector.value;
    });
</script>
<?= $this->paginationControl($this->routers,'Sliding','application/partial/paginator',['route' => 'policy']); ?>